### 🔹 Generar equipos balanceados
POST http://localhost:3000/teams/balanced
Content-Type: application/json

{
  "playerNames": [
    "Axel", "Seba Q", "Seba F", "Goro", "Luca",
    "Nico", "Nahue", "Naza", "Santi", "Mati P"
  ]
}
